zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
        - "2181:2181"
    labels:
        NAME: "zookeeper"

kafka:
    image: "wurstmeister/kafka"
    environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.50.5
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
        - "9092:9092"
    labels:
        NAME: "kafka"
    links:
        - zookeeper
